export const actionTypes: {
  FOCUS_ITEM: '__FOCUS_ITEM';
  FOCUS_PREV_ITEM: '__FOCUS_PREV_ITEM';
  FOCUS_NEXT_ITEM: '__FOCUS_NEXT_ITEM';
  MOVE_SELECTION: '__MOVE_SELECTION';
  ADD_AFTER_ITEM: '__ADD_ITEM';
  UPDATE_ITEM: '__UPDATE_ITEM';
  INDENT_ITEM: '__INDENT_ITEM';
  UNINDENT_ITEM: '__UNINDENT_ITEM';
  DESTROY_ITEM: '__DESTROY_ITEM';
  CANCEL_ITEM: '__CANCEL_ITEM';
} = {
  FOCUS_ITEM: '__FOCUS_ITEM',
  FOCUS_PREV_ITEM: '__FOCUS_PREV_ITEM',
  FOCUS_NEXT_ITEM: '__FOCUS_NEXT_ITEM',
  MOVE_SELECTION: '__MOVE_SELECTION',
  ADD_AFTER_ITEM: '__ADD_ITEM',
  UPDATE_ITEM: '__UPDATE_ITEM',
  INDENT_ITEM: '__INDENT_ITEM',
  UNINDENT_ITEM: '__UNINDENT_ITEM',
  DESTROY_ITEM: '__DESTROY_ITEM',
  CANCEL_ITEM: '__CANCEL_ITEM',
};
