export const actionTypes: {
  [key: string]: string;
} = {
  FOCUS_ITEM: '__FOCUS_ITEM',
  ADD_ITEM: '__ADD_ITEM',
  UPDATE_ITEM: '__UPDATE_ITEM',
  SHIFT_ITEM: '__SHIFT_ITEM',
  UNSHIFT_ITEM: '__UNSHIFT_ITEM',
  DELETE_ITEM: '__DELETE_ITEM',
  CANCEL_ITEM: '__CANCEL_ITEM',
  PREPEND_ITEM: '__PREPEND_ITEM',
  APPEND_ITEM: '__APPEND_ITEM',
};
