export const actionTypes: {
  FOCUS_ITEM: '__FOCUS_ITEM';
  FOCUS_PREV_ITEM: '__FOCUS_PREV_ITEM';
  FOCUS_NEXT_ITEM: '__FOCUS_NEXT_ITEM';
  ADD_AFTER_ITEM: '__ADD_ITEM';
  REMOVE_ITEM: '__REMOVE_ITEM';
  TURN_INTO: '__TURN_INTO';
  CONCAT_ITEM: '__CONCAT_ITEM';
  SPLIT_ITEM: '__SPLIT_ITEM';

  UPDATE_ITEM: '__UPDATE_ITEM';
  INDENT_ITEM: '__INDENT_ITEM';
  UNINDENT_ITEM: '__UNINDENT_ITEM';
} = {
  FOCUS_ITEM: '__FOCUS_ITEM',
  FOCUS_PREV_ITEM: '__FOCUS_PREV_ITEM',
  FOCUS_NEXT_ITEM: '__FOCUS_NEXT_ITEM',
  ADD_AFTER_ITEM: '__ADD_ITEM',
  REMOVE_ITEM: '__REMOVE_ITEM',
  TURN_INTO: '__TURN_INTO',
  CONCAT_ITEM: '__CONCAT_ITEM',
  SPLIT_ITEM: '__SPLIT_ITEM',

  UPDATE_ITEM: '__UPDATE_ITEM',
  INDENT_ITEM: '__INDENT_ITEM',
  UNINDENT_ITEM: '__UNINDENT_ITEM',
};
